apiVersion: apps/v1
kind: Deployment
metadata:
  name: sycamore-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sycamore-api
  template:
    metadata:
      labels:
        app: sycamore-api
    spec:
      containers:
        - name: api
          image: node:18-alpine
          command:
            - node
            - -e
            - |
              setInterval(() => {
                console.log("API running");
              }, 1000)
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            exec:
              command: ["node", "-e", "process.exit(0)"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["node", "-e", "process.exit(0)"]
            initialDelaySeconds: 15
            periodSeconds: 20
